### ISSUE TITLE
No response for "don't have driver's license".

### ISSUE THREAD

**Issue by SpadesNeil** [JTSwagger/GoogleBot#22]
#### Brief description of the issue
Customer can say "I don't even have a driver's license" but the bot will still go into the intro rather than end the call.

#### What you expected to happen
Cheryl to end the call. We can't offer car insurance quotes to a dude who doesn't have a car.

#### What actually happened
Cheryl doesn't understand this, and continues.

#### Steps to reproduce
1.) Say "I don't have a driver's license" after intro
2.) Watch as the bot continues with the call

#### Additional info:
 - **Bot Revision**: Pre-Github
 - **Anything else you may wish to add**: (Related issues, for example.)

**Comment by JTSwagger** [comment]
Added "don't even have" to options under no car/licence/insurance and "don't have a license" and 'have no  license" and "ain't got no license"

**Comment by SpadesNeil** [comment]
Resolved by https://github.com/JTSwagger/GoogleBot/commit/ff71f7e4466bd770ad2210d34e015fb09d8034b6
